const MOVIES ={
    "movies" :[
 {
 "Title": "Star Wars: Episode IV - A New Hope",
 "Genre": "Action, Adventure, Fantasy, Sci-Fi,Drama",
 "Language": "English",
 "Plot": "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
 "Poster": "https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
 "Runtime": "121 min",
 "Type": "Long",
 },
 
 { 
 "Title": "Harry Potter and the Deathly Hallows: Part 2",
  "Genre": "Adventure, Drama, Fantasy, Mystery",
 "Language": "English",
 "Plot": "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.",
 "Poster": "https://m.media-amazon.com/images/M/MV5BMjIyZGU4YzUtNDkzYi00ZDRhLTljYzctYTMxMDQ4M2E0Y2YxXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
 "Runtime": "130 min",
 "Type": "Long",
 },
 
 {
"Title": "The Conjuring",
"Genre": "Horror, Mystery, Thriller",
"Language": "English, Latin",
"Plot": "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
"Poster": "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_SX300.jpg",
"Runtime": "112 min",
"Type": "Long",
},
{
"Title": "My Neighbor Totoro",
"Genre": "Animation, Family, Fantasy",
"Language": "Japanese",
"Plot": "When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.",
"Poster": "https://m.media-amazon.com/images/M/MV5BNTdiOTQ0YmUtOGE3YS00NDg5LWI3YTEtNDAxZmE0MzRmZWM5L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
"Runtime": "86 min",
"Type": "Long",
},
 {
"Title": "Mononoke",
"Genre": "Animation, Fantasy, Horror",
"Language": "Japanese",
"Plot": "A mysterious man called the Medicine Seller travels along feudal Japan, uncovering and slaying evil spirits called Mononoke.",
"Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BODhmMjRjNDYtMDY1OC00ZTkzLTlmMWEtNzViYmYwYTYxNWVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
"Runtime": "25 min",
"Type": "Short",
 },
 {
"Title": "[Rec]",
"Genre": "Horror, Mystery, Thriller",
"Language": "Spanish, Japanese",
"Plot": "A television reporter and cameraman follow emergency workers into a dark apartment building and are quickly locked inside with something terrifying.",
"Poster": "https://m.media-amazon.com/images/M/MV5BZTJmNTZlZWUtZTQ2Yi00YTFjLWFiNzctYzFlNmZmZGMzYTlmXkEyXkFqcGdeQXVyMjQ2MTk1OTE@._V1_SX300.jpg",
"Runtime": "78 min",
"Type": "Long",
 },
 { 
"Title": "Bao",
"Genre": "Animation, Short, Family, Fantasy",
"Language": "Chinese, English",
"Plot": "A Chinese-Canadian woman suffering from empty nest syndrome gets a second shot at motherhood when one of her handmade dumplings comes alive.",
"Poster": "https://m.media-amazon.com/images/M/MV5BOGVmNDcwNGItYTQ3Ny00NjA5LTllMTMtZjUyZWYzMjJjMjVmXkEyXkFqcGdeQXVyNzMwOTY2NTI@._V1_SX300.jpg",
"Runtime": "8 min",
"Type": "Short",
},
{
"Title": "Piper",
"Genre": "Animation, Short, Family",
"Language": "None",
"Plot": "A mother bird tries to teach her little one how to find food by herself. In the process, she encounters a traumatic experience that she must overcome in order to survive.",
"Poster": "https://m.media-amazon.com/images/M/MV5BNzhhMDkwNWItMmRlMS00ODg1LTkzMzAtZGM3NTAwNzViZGU5XkEyXkFqcGdeQXVyOTI3MDg0NzA@._V1_SX300.jpg",
"Production": "Pixar Animation Studios",
"Runtime": "6 min",
"Type": "Short",
},
{
"Title": "Mamá",
"Type": "Short",
"Genre": "Short, Horror",
"Language": "Spanish",
"Plot": "A young girl wakes up and tells her sister that their mother has returned home.",
"Poster": "https://m.media-amazon.com/images/M/MV5BM2JlNjIxMjUtMWM4MS00NDA5LTkzZWUtMjMzMjAyOTU5MzU0XkEyXkFqcGdeQXVyNDE5MTU2MDE@._V1_SX300.jpg",
"Runtime": "3 min",
},
{
"Title": "Young Americans",
"Genre": "Drama",
"Language": "English",
"Plot": "This series portrays life at Rawley Summer Academy, an elite school in Connecticut where boys with a bright Ivy League future spend the summer industriously in classes and rowing training ...",
"Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTcxNTgyMDc1NF5BMl5BanBnXkFtZTcwMzk3NTY2Nw@@._V1_SX300.jpg",
"Runtime": "60 min",
"Type": "Medium",
},
{
"Title": "Day 1000",
"Type": "Short",
"Genre": "Short, Drama, Sci-Fi",
"Language": "English",
"Plot": "For 1000 days, 22-year-old David has been quarantined, alone, in an isolated cabin...until now.",
"Poster": "https://readycenterusa.files.wordpress.com/2016/06/maxresdefault.jpg?w=614",
"Runtime": "30 min",
},
{
"Title": "ReMastered: Devil at the Crossroads",
"Genre": "Documentary,Drama",
"Language": "English",
"Plot": "A look at the short, mysterious life of blues legend, Robert Johnson, who was said to have made a deal with the Devil at a crossroads in rural Mississippi.",
"Poster": "https://m.media-amazon.com/images/M/MV5BMjEzNThiYzctMDMzZi00OTViLWIyZGUtN2Q2NTE0Nzk1ODkwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
"Runtime": "48 min",
"Type": "Medium",
},
{
"Title": "Kung Fury",
"Genre": "Short, Action, Comedy, Fantasy, Sci-Fi,Drama",
"Language": "English, Swedish, German",
"Plot": "In 1985, Kung Fury, the toughest martial artist cop in Miami, goes back in time to kill the worst criminal of all time - Kung Führer, a.k.a. Adolf Hitler.",
"Poster": "https://m.media-amazon.com/images/M/MV5BMjQwMjU2ODU5NF5BMl5BanBnXkFtZTgwNTU1NjM4NTE@._V1_SX300.jpg",
"Runtime": "30 min",
"Type": "Short",
},
{
"Title": "Never Hike Alone",
"Genre": "Horror, Thriller",
"Language": "English",
"Plot": "A hiker's survival skills are put to the test, when he stumbles upon the remains of an old abandoned camp and discovers its long dark secrets.",
"Poster": "https://m.media-amazon.com/images/M/MV5BZTU1YjdlY2ItNGUwZC00ODBjLTkzMTEtZDA0Y2M0MjM0NzAyXkEyXkFqcGdeQXVyNDA5ODU0NDg@._V1_SX300.jpg",
"Runtime": "54 min",
"Type": "Medium",
},
{
"Title": "Tangled: Before Ever After",
"Genre": "Animation, Adventure, Comedy, Family, Fantasy, Musical",
"Language": "English",
"Plot": "As Rapunzel prepares for her coronation as Princess of Corona, one unforgettable night will change her hair again!",
"Poster": "https://m.media-amazon.com/images/M/MV5BYzZkYzIwNGUtZmNiMC00NGQ1LWFmN2UtODU0YzhiYjBjYmQyXkEyXkFqcGdeQXVyNjg3MDM4Mzc@._V1_SX300.jpg",
"Runtime": "55 min",
"Type": "Medium",
},
{
"Title": "The Spirit of Haddonfield",
"Genre": "Short, Horror",
"Language": "English",
"Plot": "THE SPIRIT OF HADDONFIELD is the newest project from filmmaker Rene Rivas. It is an extremely well produced short fan film that exists in an alternate Halloween H20 universe. The Spirit of ...",
"Poster": "https://m.media-amazon.com/images/M/MV5BOTIzZjk0MTAtZDc5ZC00OTYzLWE0MmEtMGU0OTdlNTFmNzM1XkEyXkFqcGdeQXVyMjk2OTY0Nzg@._V1_SX300.jpg",
"Runtime": "20 min",
"Type": "Short"
},

{
"Title": "Shôjo tsubaki: Chika gentô gekiga",
"Genre": "Animation, Drama, Horror",
"Language": "Japanese",
"Plot": "A little orphaned girl joins a freak-show circus troupe whose members rape and abuse her. She then finds a glimmer of hope in the enigmatic magician who joins the group.",
"Poster": "https://m.media-amazon.com/images/M/MV5BZGVhNGVjZjEtMTUyNS00NmEwLWE0ODMtNzhkZTk4Njc1ZWEzXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg",
"Runtime": "56 min",
"Type": "Medium",
},

{
"Title": "Dragon Ball Z: Fusion Reborn",
"Genre": "Animation, Action, Sci-Fi",
"Language": "Japanese",
"Plot": "The universe is thrown into dimensional chaos as the dead come back to life. Now Goku and Vegeta must track down the cause of this uproar.",
"Poster": "https://m.media-amazon.com/images/M/MV5BOWRiNDJlNzAtZjk3ZC00NDhjLTlmNzMtNTJiNDM2NDU3NjI2XkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg",
"Runtime": "51 min",
"Type": "Medium",
},

{
"Title": "The Call of Cthulhu",
"Genre": "Fantasy, Horror, Mystery, Thriller",
"Language": "English, French, Spanish, Italian, German",
"Plot": "While sorting the affairs of his late Uncle, a man accidentally stumbles across a series of dark secrets connected to an ancient horror waiting to be freed.",
"Poster": "https://m.media-amazon.com/images/M/MV5BOTU3OTU1MDkyNF5BMl5BanBnXkFtZTcwODEyNDk5OA@@._V1_SX300.jpg",
"Runtime": "47 min",
"Type": "Medium",
},
{
"Title": "Five Nights at Freddy's 4 the Movie",
"Genre": "Horror",
"Language": "English",
"Plot": "One day a child goes to Freddy Fazbear's Pizza restaurant. The next day strange things start to happen. A package arrives at his front door, an invitation to an anonymous birthday party. ...",
"Poster": "https://m.media-amazon.com/images/M/MV5BZGIwNzc4YmItZTkwNi00ZTg4LThiNDUtNmJiODYyY2Q5Mjc0L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNzA3NDI3NTY@._V1_SX300.jpg",
"Runtime": "60 min",
"Type": "movie",
}


]};;